name: cnmecab
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-56.0.dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  intl: ^0.19.0
  image_picker: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  firebase_storage: ^12.0.1
  flutter_dialogs: ^3.0.0
  fluttertoast: ^8.2.2
  firebase_messaging: ^15.0.1
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^17.1.2
  firebase_app_check: ^0.3.0+1
  http: ^1.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.14.0
  fake_cloud_firestore: ^3.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
