// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwJPgVEwbpPp-sdH71jXeN8_67vSu_6g',
    appId: '1:731619838643:web:1d36fbea5aa8eaea177ec6',
    messagingSenderId: '731619838643',
    projectId: 'cn-mecab-3c43c',
    authDomain: 'cn-mecab-3c43c.firebaseapp.com',
    storageBucket: 'cn-mecab-3c43c.appspot.com',
    measurementId: 'G-R2GQ9Z9KNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnXvZlQCgghlGU7ySlv2GDhkhwRPJAJNI',
    appId: '1:731619838643:android:9243bf119e421bca177ec6',
    messagingSenderId: '731619838643',
    projectId: 'cn-mecab-3c43c',
    storageBucket: 'cn-mecab-3c43c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmopU12ovBJ8qv_55SvDELbhNUqGEY490',
    appId: '1:731619838643:ios:ae81af5716c3a2dd177ec6',
    messagingSenderId: '731619838643',
    projectId: 'cn-mecab-3c43c',
    storageBucket: 'cn-mecab-3c43c.appspot.com',
    iosClientId: '731619838643-7tdfcvmiaogv4q22sgrkgostj5m1ip4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnmecab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmopU12ovBJ8qv_55SvDELbhNUqGEY490',
    appId: '1:731619838643:ios:9f942c98ffc53230177ec6',
    messagingSenderId: '731619838643',
    projectId: 'cn-mecab-3c43c',
    storageBucket: 'cn-mecab-3c43c.appspot.com',
    iosClientId: '731619838643-1cpjrnogm73puqae8njjv810p4s8d936.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnmecab.RunnerTests',
  );
}
